<?php

// ######## INICIO MODALIDAD DE EMISIÓN FISCAL ########
return [
    'operation_tables' => [
        'account_movements',
        'bank_account_transactions',
        'bank_loans',
        'cash',
        'cash_documents',
        'contracts',
        'devolutions',
        'dispatches',
        'documents',
        'expenses',
        'fixed_asset_purchases',
        'global_payments',
        'guides',
        'income',
        'inventories',
        'inventories_transfer',
        'inventory',
        'inventory_kardex',
        'mill',
        'order_forms',
        'order_notes',
        'packaging',
        'payment_links',
        'perceptions',
        'production',
        'purchase_orders',
        'purchase_quotations',
        'purchase_settlements',
        'purchases',
        'quotations',
        'retentions',
        'sale_notes',
        'sale_opportunities',
        'summaries',
        'technical_services',
        'tips',
        'transactions',
        'voided',
    ],
];
// ######## FIN MODALIDAD DE EMISIÓN FISCAL ########
